### ISSUE TITLE
Jodconverter not working with spring-boot 3

### ISSUE THREAD

**Issue by aalhabib001** [jodconverter/jodconverter#320]
Hi,
I am trying to upgrade the version of spring boot to 3.0.0. But the jodconverter not works with 3.0.0.
If I downgraded to spring-boot 2.7.x or below 3.0.0, then I don't face any problems.

The error I faces: 

> _Consider defining a bean of type 'org.jodconverter.core.DocumentConverter' in your configuration._

![image](https://user-images.githubusercontent.com/41731413/206925856-eb689d51-694c-4d6e-8f1a-991e852c4ce3.png)

I reproduced the bug on a sample application. [You can find the codebase here.](https://github.com/aalhabib001/demo-doc-converter) 
You can try with Spring-Boot versions 2.7.4 & 3.0.0 to check the bug.

So, My question is, "Is this library compatible with spring-boot 3"? 

Thanks in Advance.

**Comment by imtiazShakil** [comment]
hi, I'm also facing the same issue. the library works fine upto spring boot 2.7.4 but as soon as I upgrade it stops working...

**Comment by sbraconnier** [comment]
This is the next one I'll fix! Stay tuned...

**Comment by sbraconnier** [comment]
Okay!! Well.... Spring boot 3.0+ requires java17 as baseline.... See [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes)... Please tell me, what should I do??? (jodconverter baseline is java8)

**Comment by TimMeissner** [comment]
Just use jodconverter-local instead of spring and set up the office manager yourself. Works fine for me on spring boot 3

**Comment by EugenMayer** [comment]
> Okay!! Well.... Spring boot 3.0+ requires java17 as baseline.... See [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes)... Please tell me, what should I do??? (jodconverter baseline is java8)

Correct me, but even though that jodconverter is compiled under java8, it will run under java17. Yes, there are exceptions for this statement (things that have been removed with 9+ / 11+ and need to be included via library instead of relying that on an jre8 it is shiped with the JRE) - but dealing with that upfront while still compiling against / target 8, should still make jodconverter compatible to both, spring boot 3.0 with a j17 baseline and whatever running java8.

For example, all jodconverter examples i made in https://github.com/jodconverter/docker-image-jodconverter-examples are runniung under jre17 - for very good reasons (j8 has horrible docker compatiblity which really affects jodconverter in a special way too).

II think sb 3.0 compat is more about the spring boot starter projects adopting what sb 3.0 changed, less then adopting what j17 implied. 

Should i be wrong with all that, there is simply the option in having 2 spring boot starter projects, one for sb <3.0 with j8 as target, and one for sb3.0+ with java17 as targret (i do not think this is needed though).

That said, to be honest, considering what jodconverter is and does, i think it is more then time think about moving to java 17 or java11. Be it optional, streams jakarta and all this, it is time to move on and let java8 go. This is of course a different topic then "a technical need to move on due to spring boot 3.0" - i think the latter does not require jodconverter to move to j17.

**Comment by EugenMayer** [comment]
I went forward and tried to integrate https://github.com/EugenMayer/officeconverter on spring boot with jodconverter.

I could not get it running initially since the OfficeManager was missing. It did not sounded to be an issue of java version/spring boot version. Still i upgraded jodconverter sb to 3.0.1 and also the java version to 17 ( https://github.com/jodconverter/jodconverter/tree/feature/spring-boot-3.0 )

Using a composite build (i did not publish anything) it still does fail with the same reason - which is what i was expecting.

I'am yet not sure how and why, but the AutoConfiguration of the jodconverter spring boot. Debugging JodConverterLocalAutoConfiguration it ineeded is never created at all, even though i use `jodconverter.local.enabled=true` - even removing all the conditions did not help.

Double checking `spring.factories`

```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration,\
org.jodconverter.boot.autoconfigure.JodConverterRemoteAutoConfiguration
```

I looks just fine. So i assume, we do not need to upgrade our starter here to sb 3.0.1 or to java 17, we need to find out why the auto configuration is yet not working under sb 3.0.1 at all

**Comment by EugenMayer** [comment]
Ok the reasons `spring.factories` was deprecated in sb 2 and removed in 3 - so that is why the auto-configuration stopped working - i adopted this in https://github.com/jodconverter/jodconverter/tree/feature/spring-boot-3.0 but could not get it running yet.

**Comment by EugenMayer** [comment]
I finished the implementation, downgraded to 2.7.7 and java 8 again and it works.

**Comment by imtiazShakil** [comment]
Hi, look like the code has been updated to support spring boot 3, but is this available in maven repository? 

Looking forward to update!

**Comment by sbraconnier** [comment]
@imtiazShakil Not yet, but it will be within within a week.
